### ISSUE TITLE
Typos in SummationByPartsOperators.jl/src/SBP_coefficients/Mattsson2012.jl

### ISSUE THREAD

**Issue by chrisstolk** [ranocha/SummationByPartsOperators.jl#111]
Dear dr. Ranocha,
Please check line 519 of SummationByPartsOperators.jl/src/SBP_coefficients/Mattsson2012.jl. After the text    d414    the text    *b[4]     should be added.
Similar in lines 520, 527, 528,  536, 537, 542.
Similar in code blocks in lines 547-597, lines 628-678, lines 681-731.

I hope this is useful.

Best regards,
Chris Stolk (University of Amsterdam)

**Comment by ranocha** [comment]
Thanks a lot! I will fix these typos soon
