### ISSUE TITLE
Non-central periodic operators?

### ISSUE THREAD

**Issue by jlchan** [ranocha/SummationByPartsOperators.jl#136]
Would it be possible to support upwind/downwind stencils for periodic operators? For example, I am hoping to use the interior stencil of `Mattsson2017(:minus/:plus)` but for a periodic domain. I would very much like to take advantage of the specialized `mul!` if possible. 

Thanks!

**Comment by ranocha** [comment]
That's already possible by specifying a `left_offset`, see https://ranocha.de/SummationByPartsOperators.jl/stable/api_reference/#SummationByPartsOperators.periodic_derivative_operator

**Comment by ranocha** [comment]
I'm on my phone right now so I can't check whether these give you exactly the same coefficients Ken Mattsson used in the interior but I think they should

**Comment by ranocha** [comment]
Please come back to me if there are any questions or problems. I should probably mention this feature a bit more prominently in the docs, too...

**Comment by jlchan** [comment]
The `Q` matrix entries indeed appear to be the same! The (non-boundary) mass matrix entries differ slightly between the operators, but I think that is to be expected. Thanks for the tip!

**Comment by ranocha** [comment]
Do you use the same number of nodes? To get equivalent results, you need to use one node less for periodic operators since the right boundary node is set by periodicity. Then, you should get the same `D` and `M` in the interior.

**Comment by jlchan** [comment]
That completely explains it. Thanks!
