### ISSUE TITLE
Support for non-uniform grids?

### ISSUE THREAD

**Issue by aditya-sengupta** [ranocha/SummationByPartsOperators.jl#206]
I can't find anything about supporting non-uniform grids in the documentation - is this a supported feature? I think it'd just involve rescaling the operator coefficients according to the differences between grid points, so I could do this with the matrix forms of the operators. It'd just be a matter of making the non-matrix operators work that way.

**Comment by ranocha** [comment]
Arbitrary non-uniform grids are not widely supported. The only method that comes to my mind is `fornberg` - which can be used to compute FD coefficients on arbitrary grids, see https://ranocha.de/SummationByPartsOperators.jl/stable/api_reference/#SummationByPartsOperators.fornberg-Union{Tuple{T},%20Tuple{Vector{T},%20Int64}}%20where%20T

However, it basically  only works with periodic grids. For non-periodic grids, this package focuses on summation by parts (SBP) operators which come with a special boundary closure for stability. It is non-trivial to provide such a special boundary closure for arbitrary grids. However, some SBP operators use non-uniform grids near the boundaries, e.g., 
- cut-cell operators of Sharan, Brady, and Livescu (see https://ranocha.de/SummationByPartsOperators.jl/stable/api_reference/#SummationByPartsOperators.SharanBradyLivescu2022)
- the optimzied operators of Mattsson et al. (https://ranocha.de/SummationByPartsOperators.jl/stable/api_reference/#SummationByPartsOperators.MattssonAlmquistVanDerWeide2018Accurate, https://ranocha.de/SummationByPartsOperators.jl/stable/api_reference/#SummationByPartsOperators.MattssonAlmquistVanDerWeide2018Minimal, https://ranocha.de/SummationByPartsOperators.jl/stable/api_reference/#SummationByPartsOperators.MattssonAlmquistCarpenter2014Optimal)
