### ISSUE TITLE
Discontinuous and continuous coupling for second derivatives

### ISSUE THREAD

**Issue by jbiffl** [ranocha/SummationByPartsOperators.jl#246]
I recently found your package and have been really enjoying how simple it is to use, but I'm having trouble figuring out how to use cell coupling for an advection/diffusion equation. 

From what I can tell, continuous coupling is supported for first and second derivatives, but 5 argument mul!() is unsupported for continuous coupling.
Discontinuous coupling is supported for 5 argument mul!(), but only for first derivatives. 

Using continuous coupling since second derivatives are supported, I thought I was using the three argument since I had used `mul!(du, D, u)` but both that and  `du = D * u`, where `D = -v0*D1 + diff*D2`, return the same error 
```ArgumentError: 5-arg `mul!` does not support continuously coupled operators at the moment.``` 
so it seems like they both get automatically turned into a five argument mul!() during compilation. 

Is there a way around this, or is advection+diffusion not supported for any kind of coupling?

Thanks!

**Comment by ranocha** [comment]
Thanks! Nice to know that this package is useful for you.

There could be several options for coupling second-derivative operators discontinuously, e.g., BR1 (Bassi-Rebay 1), BR2, local DG variants, ... I just didn't have a need to implement them for my own research so far.

I am not sure I understand the problem you get. 3-argument `mul!` works for me for continuously coupled second-derivative operators, e.g.,

```julia
julia> using SummationByPartsOperators

julia> D = legendre_second_derivative_operator(xmin = 0.0, xmax = 1.0, N = 3)
Second derivative operator {T=Float64} on 3 Lobatto Legendre nodes in [0.0, 1.0]

julia> mesh = UniformPeriodicMesh1D(xmin = 0.0, xmax = 1.0, Nx = 3)
UniformPeriodicMesh1D{Float64} with 3 cells in (0.0, 1.0)

julia> D2 = couple_continuously(D, mesh)
Second derivative operator {T=Float64} on 3 Lobatto Legendre nodes in [0.0, 1.0]
coupled continuously on UniformPeriodicMesh1D{Float64} with 3 cells in (0.0, 1.0)

julia> Matrix(D2)
6×6 Matrix{Float64}:
 -126.0   72.0    -9.0    0.0    -9.0   72.0
   36.0  -72.0    36.0    0.0     0.0    0.0
   -9.0   72.0  -126.0   72.0    -9.0    0.0
    0.0    0.0    36.0  -72.0    36.0    0.0
   -9.0    0.0    -9.0   72.0  -126.0   72.0
   36.0    0.0     0.0    0.0    36.0  -72.0

julia> u = rand(size(D2, 2))
6-element Vector{Float64}:
 0.8410591279283173
 0.2354756207576334
 0.34416918136865526
 0.6460314284075914
 0.5415992443669859
 0.21547126895380686

julia> du = zero(u)
6-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

julia> mul!(du, D2, u)
6-element Vector{Float64}:
 -81.47718989136511
  25.71397444014142
   7.6592653367879
 -14.626599518863516
 -16.880365363892324
  34.26177003795686
```

If it doesn't work for you, please provide a minimal working example (MWE) so that I can have a look.

**Comment by jbiffl** [comment]
Thanks for your reply! I've attached a MWE below which is representative of my code and generates the same error I've been getting. Is it because I'm using the linear combination of two operators?

```
using SummationByPartsOperators, LinearAlgebra

N = 5 
xmin, xmax = 0.0, 1.0 
D1 = upwind_operators(Mattsson2017, accuracy_order=2, xmin=xmin, xmax=xmax, N=N).minus #First derivative upwind operator
D2 = derivative_operator(MattssonNordström2004(), derivative_order=2, accuracy_order=2, xmin=xmin, xmax=xmax, N=N) #second derivative operator

mesh = UniformMesh1D(xmin=xmin, xmax=xmax, Nx = 10)
D1cc = couple_continuously(D1, mesh)#, Val(:minus))
D2cc = couple_continuously(D2, mesh)
D_cc = D4+D5
u0_func1(x) = 0
test_u = compute_coefficients(u0_func1, D6)
u0 = rand(size(test_u,1))
du0 = copy(u0)
mul!(du0, D6, u0)


```

This gives the following error: 
```
ERROR: ArgumentError: 5-arg `mul!` does not support continuously coupled operators at the moment.
Stacktrace:

1. mul!(dest::Vector{…}, cD::SummationByPartsOperators.UniformNonperiodicCoupledOperator{…}, u::Vector{…}, α::Float64, β::Float64) at [coupling.jl]

2. macro expansion at [general_operators.jl]

3. macro expansion at [Unrolled.jl]

4. macro expansion at [general_operators.jl]

5. macro expansion at [Unrolled.jl]

6. mul!(dest::Vector{…}, combi::SummationByPartsOperators.LinearlyCombinedDerivativeOperators{…}, u::Vector{…}, α::Float64) at [Unrolled.jl]

7. mul!(dest::Vector{…}, D::SummationByPartsOperators.LinearlyCombinedDerivativeOperators{…}, u::Vector{…}) at [general_operators.jl]

8. top-level scope at [Untitled-2]
```

**Comment by ranocha** [comment]
I guess you meant something like

```julia
using SummationByPartsOperators, LinearAlgebra
N = 5
xmin, xmax = 0.0, 1.0
D1 = derivative_operator(Mattsson2017(:minus); derivative_order=1, accuracy_order=2, xmin, xmax, N)
D2 = derivative_operator(MattssonNordström2004(); derivative_order=2, accuracy_order=2, xmin, xmax, N)
mesh = UniformMesh1D(xmin = xmin, xmax = xmax, Nx = 3)
D1cc = couple_continuously(D1, mesh)
D2cc = couple_continuously(D2, mesh)
Dcc = D1cc + D2cc
u = randn(size(Dcc, 2)); du = similar(u);
mul!(du, Dcc, u)
```

? Your code throws

```julia
julia> D_cc = D4+D5
ERROR: UndefVarError: `D4` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[9]:1

julia> test_u = compute_coefficients(u0_func1, D6)
ERROR: UndefVarError: `D6` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[11]:1
```


Yes, the problem is that you're using the linear combination of the two operators. To make it non-allocating, one needs the 5-arg `mul!` internally when calling the 3-arg `mul!` with the linearly combined operators. Everything should work if you just call 3-arg `mul!` with each operator individually. To make everything non-allocating, you will need a temporary cache to store the results of one 3-arg `mul!` call.

**Comment by ranocha** [comment]
Thus, this is basically the same as https://github.com/ranocha/SummationByPartsOperators.jl/issues/145

**Comment by jbiffl** [comment]
Thank you for the clarification! Your reinterpretation of my code is correct, that is what I was attempting. I missed those lines when I was renaming variables to try and make it more clear. I'll do as you have suggested.

Thanks!

**Comment by ranocha** [comment]
Thanks! Please let me know if I can help you in another way. I would also be happy to know when you use this package and publish results with - I can advertise it in the docs if you like
